version: "3.1"
services:
  totem-postgres:
      build:
        context: .
        dockerfile: docker/database/Dockerfile
      container_name: totem-postgres
      volumes:
        - ./docker/database/postgres:/application/
        - ./docker/database/seeder.sql:/application/seeder.sql
        - ./docker/database/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      environment:
        - POSTGRES_USER=totem
        - POSTGRES_PASSWORD=totem
        - POSTGRES_DB=totem
        - PGDATA=/application/postgres
      ports:
        - "5433:5432"
      networks:
        - default

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: techchallenge@g60.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./docker/database/pgadmin/:/var/lib/pgadmin
    links:
      - totem-postgres
    ports:
      - "8000:80"
    networks:
      - default

  totem-api:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: totem-api
    volumes:
      - ./application:/var/www
      - ./docker/bin:/var/bin
    command: sh -c "npm install && chown -R www-data:www-data /var/www"
    ports:
      - "80:80"
    links:
      - totem-postgres
    networks:
      - default

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
volumes:
  dbdata:
    driver: local