apiVersion: v1
kind: Service
metadata:
  labels:
    run: totem-postgres
  name: totem-postgres
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5432
      nodePort: 31001
  selector:
    service: totem-postgres