apiVersion: v1
kind: ConfigMap
metadata:
  name: totem-configmap
data:
  POSTGRES_PASSWORD: totem
  POSTGRES_USER: totem
  POSTGRES_DB: totem
  PGDATA: /application/postgres
  POSTGRES_HOST_AUTH_METHOD: trust
